### ISSUE TITLE
Mask and Matte layer not working

### ISSUE THREAD

**Issue by OmidID** [yinyue200/LottieSkiaSharp#1]
Mask and Matte layer are not working. you can test `lottiefiles.com - ATM.json` for mask layer and `swiftkey-logo.json` for matte layers

**Comment by OmidID** [comment]
@yinyue200 Good job 👍 
I pull the last version and i can see all animation are slow. i think you set fps somewhere for test, right?

**Comment by yinyue200** [comment]
@OmidID yes, I will restore it
